### ISSUE TITLE
Consistent capitalization for Institution taxonomy labels

### ISSUE THREAD

**Issue by mandiwise** [redacademy/riipen-fall-2016#5]
Please consistently user uppercase labels in your Institution custom taxonomy labels:

https://github.com/redacademy/riipen-fall-2016/blob/master/plugins/riipen-functionality/lib/functions/taxonomies.php

**Comment by ringong95** [comment]
The Institution taxonomy has been renamed to a more semantically appropriate name and has consistent capitalization.
