### ISSUE TITLE
Search page PHP issue

### ISSUE THREAD

**Issue by c-oh** [redacademy/riipen-fall-2016#50]
Saw this when I searched for Jane Doe in google chrome search bar:

Catchable fatal error: Object of class WP_Error could not be converted to string in /home/redacade/public_html/riipen/wp-content/themes/riipen/template-parts/content-search.php on line 22

**Comment by c-oh** [comment]
Also, does the search page need styling? or is it already styled

**Comment by ringong95** [comment]
The search page is half styled in a really odd way. Remkind me on monday to bug sophie about it again if we are not done it
