### ISSUE TITLE
Video not loading (google chrome desktop)

### ISSUE THREAD

**Issue by c-oh** [redacademy/riipen-fall-2016#58]
Failed to load resource: the server responded with a status of 412 (Precondition Failed)

Got this error in the console log about the video background

**Comment by ringong95** [comment]
I don't seem to be getting this issue. When it is happening for you? and does the video show when it happens?

**Comment by c-oh** [comment]
It goes grey and nothing shows up

**Comment by ringong95** [comment]
uh i cant seem to get it to not show up.
