### ISSUE TITLE
Disambiguate "Institutions" CPT and taxonomy

### ISSUE THREAD

**Issue by mandiwise** [redacademy/riipen-fall-2016#6]
Please rename your "Institution" custom taxonomy...it's confusing to have a CPT and taxonomy named the same thing. Perhaps call it "Institution Type" instead.

Please delete all institutions from that existing taxonomy before you do this (they will be orphaned in the database otherwise). Then transfer those terms over to your new "Institution Type" taxonomy.

Remember that you will need to rename applicable template and flush your permalinks once you do this.

ALTERNATIVELY, if you actually need to connect Educator posts to Institution posts, you will need to use the Posts 2 Post plugin (instead of a taxonomy). Please talk to me if you need further clarification.

**Comment by ringong95** [comment]
I added a new taxonomy with a more descriptive name
