### ISSUE TITLE
Extra padding in footer issue

### ISSUE THREAD

**Issue by jonathanfunk** [redacademy/riipen-fall-2016#65]
There's so much padding in the footer that the footer information has been pushed out.

**Comment by c-oh** [comment]
would you mind taking a screenshot? thanks! it looks normal on my computer so it would be best if i could see it in different screen sizes

**Comment by jonathanfunk** [comment]
![screen shot 2016-12-12 at 9 55 10 am](https://cloud.githubusercontent.com/assets/20465505/21110226/344ff802-c051-11e6-9651-a604a6167330.png)
This is what it looks like at 1920X1200 resolution.

**Comment by jonathanfunk** [comment]
I'll see what I can do.

**Comment by jonathanfunk** [comment]
Padding percentage is the culprit.
