### ISSUE TITLE
Use HTML escape characters where appropriate

### ISSUE THREAD

**Issue by mandiwise** [redacademy/riipen-fall-2016#8]
As an example, please see:

https://github.com/redacademy/riipen-fall-2016/blob/master/themes/riipen/archive-organizations.php#L11

Or:

https://github.com/redacademy/riipen-fall-2016/blob/master/themes/riipen/front-page.php#L84

**Comment by c-oh** [comment]
Replaced all of the back buttons and front page symbols with escape tags.
