### ISSUE TITLE
Empty divs are a hack, please fix

### ISSUE THREAD

**Issue by mandiwise** [redacademy/riipen-fall-2016#9]
As an example, please see:

https://github.com/redacademy/riipen-fall-2016/blob/master/themes/riipen/archive-organizations.php#L24

**Comment by ringong95** [comment]
@mandiwise For that example i've asked Rose and exampled how they are a substitute for an image with functionality she said it would be ok. However before I close this issue i wanted to ask you for your opinion.

**Comment by c-oh** [comment]
Removed empty divs from educator page of code
